// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class BrowserGameTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void browserGame() {
    driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/");
    driver.manage().window().setSize(new Dimension(1057, 691));
    driver.findElement(By.cssSelector(".P9dW9p")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("emailgetajob@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1187342a");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".P32btb"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".P3Y0hn")).click();
    driver.findElement(By.cssSelector(".P1MFGS")).sendKeys(Keys.ENTER);
    driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/");
    driver.manage().window().setSize(new Dimension(1092, 993));
    driver.findElement(By.cssSelector(".P9dW9p")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//span[contains(.,\'Sign in with Facebook\')]")).click();
    vars.put("win8300", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    {
      WebElement element = driver.findElement(By.cssSelector(".P32btb"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".P3Y0hn")).click();
    driver.findElement(By.cssSelector(".P1MFGS")).click();
    driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/");
    driver.manage().window().setSize(new Dimension(1057, 691));
    driver.findElement(By.cssSelector(".P9dW9p")).click();
    driver.findElement(By.xpath("//button[contains(.,\'Sign in with Google\')]")).click();
    vars.put("root", driver.getWindowHandle());
  }
}
