// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('BrowserGame*', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('BrowserGame*', async function() {
    await driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    await driver.setRect(1057, 691)
    await driver.findElement(By.css(".P9dW9p")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("emailgetajob@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("1187342a")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.css(".P32btb"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".P3Y0hn")).click()
    await driver.findElement(By.css(".P1MFGS")).sendKeys(Key.ENTER)
    await driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    await driver.setRect(1092, 993)
    await driver.findElement(By.css(".P9dW9p")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.xpath("//span[contains(.,\'Sign in with Facebook\')]")).click()
    vars["win8300"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    {
      const element = await driver.findElement(By.css(".P32btb"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".P3Y0hn")).click()
    await driver.findElement(By.css(".P1MFGS")).click()
    await driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    await driver.setRect(1057, 691)
    await driver.findElement(By.css(".P9dW9p")).click()
    await driver.findElement(By.xpath("//button[contains(.,\'Sign in with Google\')]")).click()
    vars["root"] = await driver.getWindowHandle()
  })
})
