# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestBrowserGame():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_browserGame(self):
    self.driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    self.driver.set_window_size(1057, 691)
    self.driver.find_element(By.CSS_SELECTOR, ".P9dW9p").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("emailgetajob@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1187342a")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".P32btb")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".P3Y0hn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".P1MFGS").send_keys(Keys.ENTER)
    self.driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    self.driver.set_window_size(1092, 993)
    self.driver.find_element(By.CSS_SELECTOR, ".P9dW9p").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Sign in with Facebook\')]").click()
    self.vars["win8300"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    element = self.driver.find_element(By.CSS_SELECTOR, ".P32btb")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".P3Y0hn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".P1MFGS").click()
    self.driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    self.driver.set_window_size(1057, 691)
    self.driver.find_element(By.CSS_SELECTOR, ".P9dW9p").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign in with Google\')]").click()
    self.vars["root"] = self.driver.current_window_handle
  
