// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('BrowserGame_1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('BrowserGame_1', async function() {
    await driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    await driver.setRect(1057, 691)
    await driver.findElement(By.css(".P9dW9p")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("emailgetajob@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("1187342a")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
  })
})
