# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestBrowserGame1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_browserGame1(self):
    self.driver.get("https://plarium.com/en/strategy-games/throne-kingdom-at-war/")
    self.driver.set_window_size(1057, 691)
    self.driver.find_element(By.CSS_SELECTOR, ".P9dW9p").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("emailgetajob@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1187342a")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
  
